api-url: "https://auth.aihmc.top"

servers:
  lobby: "lobby"
  auth: "auth"

restrictions:
  allowed-commands:
    - "/login"
    - "/register"
    - "/l"
    - "/reg"

  # 验证超时设置
  registration-timeout-seconds: 120
  login-timeout-seconds: 120
  max-retry-attempts: 3
  cooldown-minutes: 10

# 标题显示设置
title-settings:
  fade-in-seconds: 1
  stay-seconds: 30
  fade-out-seconds: 1
  repeat-interval-seconds: 30

access-token: "your_bearer_token_here"